# Generated by Django 4.2.1 on 2023-07-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_patients',
            name='caller_id',
        ),
        migrations.AddField(
            model_name='agg_hhc_patients',
            name='hhc_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
