# Generated by Django 4.2.2 on 2023-07-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='Payment_type',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='Tally_Remark',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='estimate_cost',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='inc_call_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='pt_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='purpose_event_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='relation',
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='event_code',
            field=models.CharField(blank=True, max_length=640, null=True),
        ),
    ]
