# Generated by Django 4.2.2 on 2023-07-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_callers',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_patients',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_patients',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='caller_rel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_caller_relation'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='pt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_patinet_list_enquiry'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_patients',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
