# Generated by Django 4.2.2 on 2023-07-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_callers',
            name='relation',
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='caller_rel_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_caller_relation'),
        ),
        migrations.AddField(
            model_name='agg_hhc_detailed_event_plan_of_care',
            name='pt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_patinet_list_enquiry'),
        ),
    ]
