# Generated by Django 4.2.2 on 2023-07-14 12:25

from django.db import migrations, models
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0002_remove_agg_hhc_callers_relation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agg_hhc_event_plan_of_care',
            old_name='discount_percentage',
            new_name='final_cost',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_event_plan_of_care',
            name='add_discount',
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='discount_type',
            field=django_enumfield.db.fields.EnumField(default=3, enum=hhcweb.models.discount_type_enum, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='prof_prefered',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.pt_gender_enum, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='total_cost',
            field=models.IntegerField(null=True),
        ),
    ]
