# Generated by Django 4.2.2 on 2023-07-19 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0002_remove_agg_hhc_events_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_events',
            name='pt_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_patinet_list_enquiry'),
        ),
    ]
