# Generated by Django 4.2.1 on 2023-07-12 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0002_remove_agg_hhc_pincode_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_pincode',
            name='city_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_city', to_field='city_name'),
        ),
    ]
