# Generated by Django 4.2.1 on 2023-05-30 12:29

from django.db import migrations
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0002_alter_agg_hhc_services_package_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_services',
            name='Package_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Package_status_enum),
        ),
        migrations.AlterField(
            model_name='agg_hhc_services',
            name='flag',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.flag_enum),
        ),
        migrations.AlterField(
            model_name='agg_hhc_sub_services',
            name='flag',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.flag_enum),
        ),
    ]
