# Generated by Django 4.2.2 on 2023-07-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0003_agg_hhc_events_pt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_events',
            name='pt_id',
        ),
    ]
