# Generated by Django 4.2.1 on 2023-07-13 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0002_remove_agg_hhc_callers_relation_and_more'),
        ('hhcweb', '0003_agg_hhc_pincode_city_name'),
    ]

    operations = [
    ]
