# Generated by Django 4.2.1 on 2023-07-17 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0003_rename_discount_percentage_agg_hhc_event_plan_of_care_final_cost_and_more'),
        ('hhcweb', '0004_merge_20230713_1545'),
    ]

    operations = [
    ]
