# Generated by Django 4.2.1 on 2023-07-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0005_merge_20230717_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agg_hhc_professional_location',
            new_name='agg_hhc_professional_zone',
        ),
        migrations.RenameField(
            model_name='agg_hhc_professional_location_preferences',
            old_name='prof_loc_id',
            new_name='prof_zone_id',
        ),
        migrations.RenameField(
            model_name='agg_hhc_professional_zone',
            old_name='prof_loc_id',
            new_name='prof_zone_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_service_professionals',
            name='name',
        ),
        migrations.AddField(
            model_name='agg_hhc_professional_location_details',
            name='prof_zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_professional_zone'),
        ),
        migrations.AddField(
            model_name='agg_hhc_service_professionals',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_service_professionals',
            name='prof_zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_professional_zone'),
        ),
        migrations.AddField(
            model_name='agg_hhc_service_professionals',
            name='skill_set',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
