# Generated by Django 4.2.2 on 2023-07-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0005_alter_agg_hhc_events_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='event_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
