# Generated by Django 4.2.1 on 2023-07-18 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0006_rename_agg_hhc_professional_location_agg_hhc_professional_zone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_professional_scheduled',
            name='professiona_id',
        ),
        migrations.AddField(
            model_name='agg_hhc_professional_scheduled',
            name='srv_prof_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_service_professionals'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='otp_expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
