# Generated by Django 4.2.1 on 2023-07-18 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0008_alter_agg_hhc_professional_scheduled_from_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_professional_scheduled',
            name='added_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
