# Generated by Django 4.2.1 on 2023-05-30 12:49

from django.db import migrations
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0009_alter_agg_hhc_services_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_services',
            name='flag',
        ),
        migrations.AddField(
            model_name='agg_hhc_services',
            name='s1',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hhcweb.models.flag_enum),
        ),
        migrations.AlterField(
            model_name='agg_hhc_sub_services',
            name='flag',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hhcweb.models.flag_enum),
        ),
    ]
