# Generated by Django 4.2.1 on 2023-05-30 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0011_alter_agg_hhc_services_s1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_services',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_sub_services',
            name='flag',
        ),
    ]
