# Generated by Django 4.2.1 on 2023-05-31 05:34

from django.db import migrations
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0013_agg_hhc_services_tf_agg_hhc_sub_services_tf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_job_closure',
            name='status',
        ),
        migrations.AddField(
            model_name='agg_hhc_jobclosure_detail_datewise',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
    ]
