# Generated by Django 4.2.1 on 2023-05-31 06:15

from django.db import migrations
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0014_remove_agg_hhc_job_closure_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_admin_users',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_admin_users',
            name='types',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.desk_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_admin_users_modules',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_assessment_patient_list',
            name='Treatmet_Type',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hhcweb.models.Treatmet_Type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_assisted_living_booking',
            name='Facility_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Facility_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_assisted_living_booking',
            name='Patient_location',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.patient_bed_location_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_assisted_living_booking',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_attendance_details',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_avaya_extensions',
            name='is_deleted',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_caller_relation',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_callers',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_cancellation_history',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_conference_call',
            name='is_deleted',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_consent_agree_form',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_consumables',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_consumables',
            name='types',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.consumable_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_content',
            name='content_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.content_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_content',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_dash_count_details',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.active_inactive_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_detailed_event_plan_of_care',
            name='Reason_for_no_serivce',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Reason_for_no_serivce_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_detailed_event_plan_of_care',
            name='Session_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Session_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_detailed_event_plan_of_care',
            name='last_modified_by',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.last_modified_by_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_detailed_event_plan_of_care',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_device_version_info',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.active_inactive_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_doc_con',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_doctors_consultants',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.consultant_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_doctors_consultants',
            name='type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_documetns_list',
            name='isManadatory',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.truefalse_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_emp_spero',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_employees',
            name='is_login',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_employees',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_employees',
            name='types',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.employee_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_enquiry_follow_up',
            name='follow_up_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_enquiry_follow_up',
            name='is_read_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_doctor_mapping',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_doctor_mapping',
            name='types',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.types_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_job_summary',
            name='report_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.reporting_by_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_job_summary',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_job_summary',
            name='types',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.types_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_other_call',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_plan_of_care',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_professional',
            name='service_closed',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_professional',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_requirements',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_share_hcm',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='Payment_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Payment_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='discount_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.discount_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='enquiry_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.enquiry_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='estimate_cost',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.estimate_cost_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='isArchive',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='isConvertedService',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_events',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_extend_service',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.srv_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_feedback_answers',
            name='user_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.user_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_feedback_form',
            name='option_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.option_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_feedback_form',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_feedback_options',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_feedbackform1',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_gender',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_hospital_ips',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_hospitals',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure',
            name='airway',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.airway_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure',
            name='baseline',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.baseline_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure',
            name='breathing',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.breathing_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure',
            name='circulation',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.circulation_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure',
            name='service_render',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure',
            name='skin_perfusion',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.skin_perfusion_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure_consumption_mapping',
            name='consumption_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.consumption_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_job_closure_consumption_mapping',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_jobclosure_detail_datewise',
            name='added_by_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.reg_source_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_knowledge_base_documents',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_locations',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_log_for_event',
            name='Role_id',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Role_id_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_log_location_for_session',
            name='event_by_professional',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.event_by_professional_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_manager_spero',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_membership_schedule_detail',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_modules',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_no_reason_for_service',
            name='is_deleted',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_ongoing_remark_history',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_outgoing_call',
            name='is_deleted',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_patients',
            name='isVIP',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_patients',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='enquiry_from',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hhcweb.models.enquiry_from_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payment_details',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments',
            name='Add_through',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Add_through_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments_received_by_professional',
            name='OTP_verifivation',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.OTP_verifivation_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments_received_by_professional',
            name='Payment_mode',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Payment_mode_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments_received_by_professional',
            name='Payment_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Payment_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments_received_by_professional',
            name='added_by_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.reg_source_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments_received_by_professional',
            name='payment_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.payment_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_payments_received_by_professional',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_documents',
            name='isVerified',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.truefalse_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_documents',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.documents_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_media',
            name='types',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.pic_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_notification',
            name='Acknowledged',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.prof_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_scheduled',
            name='is_night_shift',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_scheduled',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_services',
            name='professional_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.professional_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_services',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_weekoff',
            name='Leave_Conflit',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Leave_Conflit_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_weekoff',
            name='Leave_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Leave_Conflit_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_professional_weekoff',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.truefalse_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_purpose_call',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_reschedule_session',
            name='added_user_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.user_types_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_reschedule_session',
            name='modified_user_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.user_types_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_reschedule_session',
            name='patient_acceptance_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.acceptance_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_reschedule_session',
            name='professional_acceptance_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.acceptance_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_reschedule_session',
            name='professional_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.professional_types_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_reschedule_session',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_restriction_for_session_complete',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.active_inactive_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_membership_registration',
            name='pt_consultant',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_membership_registration',
            name='pt_gender',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.pt_gender_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_membership_registration',
            name='reg_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.reg_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_membership_registration',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professional_details',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='OTP_verification',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='availability_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='document_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.document_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='location_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='reference_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.reference_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='reg_source',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.reg_source_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='set_location',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.set_location_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_service_professionals',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_services',
            name='is_hd_access',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_services',
            name='package_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.package_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_services',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_services',
            name='tf',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hhcweb.models.Tf_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_session',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.session_status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_source_of_enquiry',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_sp_incoming_call',
            name='is_deleted',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_specialty',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_sub_services',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_sub_services',
            name='tf',
            field=django_enumfield.db.fields.EnumField(default=1, enum=hhcweb.models.Tf_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_tc_examination',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_teleconsultation_enquiry',
            name='receiver',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.reciver_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_teleconsultation_enquiry',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_user_activity',
            name='added_by_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.added_by_type_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_user_activity',
            name='module_type',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.user_admin_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_vc_diagnosis',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_vc_fam_his',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_vc_investigation',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_vc_med_his',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_video_consulting',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='sp_ready_pause_history',
            name='is_deleted',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
        migrations.AlterField(
            model_name='sp_ready_pause_history',
            name='mode_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.Pause_Ready_enum, null=True),
        ),
        migrations.AlterField(
            model_name='sp_vc_prescription',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.is_delet_enum, null=True),
        ),
    ]
