# Generated by Django 4.2.1 on 2023-06-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0015_alter_agg_hhc_admin_users_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_services',
            name='image_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
