# Generated by Django 4.2.1 on 2023-06-07 11:10

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0016_alter_agg_hhc_services_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_hhc_app_caller_register',
            fields=[
                ('app_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField(null=True)),
                ('otp', models.IntegerField(null=True)),
                ('otp_expire_time', models.DateTimeField(null=True)),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.BigIntegerField(null=True)),
                ('alter_contact', models.BigIntegerField(null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('save_this_add', models.CharField(max_length=50, null=True)),
                ('added_date', models.DateField(auto_now=True, null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('status', django_enumfield.db.fields.EnumField(enum=hhcweb.models.active_inactive_enum, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='agg_hhc_app_family_details',
            fields=[
                ('family_member_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField(null=True)),
                ('otp', models.IntegerField(null=True)),
                ('otp_expire_time', models.DateTimeField(null=True)),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.BigIntegerField(null=True)),
                ('alter_contact', models.BigIntegerField(null=True)),
                ('Address', models.CharField(max_length=250, null=True)),
                ('save_this_add', models.CharField(max_length=250, null=True)),
                ('added_date', models.DateField(null=True)),
                ('app_user_id', models.IntegerField(null=True)),
                ('status', django_enumfield.db.fields.EnumField(enum=hhcweb.models.status_enum, null=True)),
                ('relation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hhcweb.agg_hhc_caller_relation')),
            ],
        ),
        migrations.CreateModel(
            name='agg_hhc_app_add_address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500, null=True)),
                ('app_call_reg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hhcweb.agg_hhc_app_caller_register')),
            ],
        ),
    ]
