# Generated by Django 4.2.1 on 2023-06-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0018_agg_hhc_patients_app_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_patients',
            name='caller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_callers'),
        ),
    ]
