# Generated by Django 4.2.1 on 2023-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0019_agg_hhc_patients_caller_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_hhc_state',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
