# Generated by Django 4.2.2 on 2023-06-14 09:35

from django.db import migrations, models
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0020_agg_hhc_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_hhc_documents',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Type', django_enumfield.db.fields.EnumField(enum=hhcweb.models.employee_type_enum, null=True)),
                ('User_id', models.IntegerField()),
                ('doc_name', models.CharField(max_length=100, null=True)),
                ('doucment', models.FileField(upload_to='')),
                ('verification_status', django_enumfield.db.fields.EnumField(enum=hhcweb.models.Leave_status_enum, null=True)),
                ('added_at_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
