# Generated by Django 4.2.2 on 2023-06-14 11:54

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0021_agg_hhc_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_hhc_patient_documents',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_name', models.CharField(max_length=100, null=True)),
                ('doucment', models.FileField(upload_to='')),
                ('verification_status', django_enumfield.db.fields.EnumField(enum=hhcweb.models.Leave_status_enum, null=True)),
                ('added_at_time', models.DateTimeField(null=True)),
                ('agg_sp_pt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_patients')),
            ],
        ),
        migrations.DeleteModel(
            name='agg_hhc_documents',
        ),
    ]
