# Generated by Django 4.2.1 on 2023-06-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0023_alter_agg_hhc_patient_documents_agg_sp_pt_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_sub_services',
            name='srv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_services'),
        ),
    ]
