# Generated by Django 4.2.2 on 2023-06-16 06:32

from django.db import migrations, models
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0024_alter_agg_hhc_sub_services_srv_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_hhc_app_patient_documents',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('agg_sp_pt_id', models.IntegerField(null=True)),
                ('doc_type_name', models.CharField(max_length=100, null=True)),
                ('path', models.CharField(max_length=500, null=True)),
                ('added_date', models.DateTimeField(null=True)),
                ('status', django_enumfield.db.fields.EnumField(default=1, enum=hhcweb.models.Tf_enum, null=True)),
            ],
        ),
    ]
