# Generated by Django 4.2.1 on 2023-06-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0025_agg_hhc_app_patient_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agg_hhc_patinet_list_enquiry',
            old_name='firstname',
            new_name='call_type',
        ),
        migrations.RenameField(
            model_name='agg_hhc_patinet_list_enquiry',
            old_name='lastname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='End_Date_and_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='Professional_Preferred',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='Start_Date_and_Time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='hospital_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='patient_Locality',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='patient_date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='patient_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='suffered_from',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_patinet_list_enquiry',
            name='patient_gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
