# Generated by Django 4.2.2 on 2023-06-21 05:41

from django.db import migrations, models
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0026_rename_firstname_agg_hhc_patinet_list_enquiry_call_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agg_hhc_event_requirements',
        ),
        migrations.RenameField(
            model_name='agg_hhc_event_plan_of_care',
            old_name='eve_req_id',
            new_name='doct_cons_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_event_plan_of_care',
            name='service_date',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_event_plan_of_care',
            name='service_date_to',
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='add_discount',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.yes_no_enum, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='discount_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='hosp_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='remark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='srv_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_event_plan_of_care',
            name='sub_srv_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
