# Generated by Django 4.2.2 on 2023-06-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0027_delete_agg_hhc_event_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_event_plan_of_care',
            name='doct_cons_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_doctors_consultants'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_plan_of_care',
            name='eve_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_events'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_plan_of_care',
            name='hosp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_hospitals'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_plan_of_care',
            name='srv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_services'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_plan_of_care',
            name='srv_prof_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_service_professionals'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_event_plan_of_care',
            name='sub_srv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_sub_services'),
        ),
    ]
