# Generated by Django 4.2.1 on 2023-06-26 07:05

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0028_alter_agg_hhc_event_plan_of_care_doct_cons_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agg_hhc_callers',
            old_name='phone_no',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_add_address',
            name='app_call_reg_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_callers',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_patients',
            name='app_user_id',
        ),
        migrations.AddField(
            model_name='agg_hhc_app_add_address',
            name='caller_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hhcweb.agg_hhc_callers'),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='alter_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='contact_no',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='otp_expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='save_this_add',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_callers',
            name='added_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_callers',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.active_inactive_enum, null=True),
        ),
        migrations.DeleteModel(
            name='agg_hhc_app_caller_register',
        ),
    ]
