# Generated by Django 4.2.1 on 2023-06-27 09:25

from django.db import migrations
import django_enumfield.db.fields
import hhcweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0029_rename_phone_no_agg_hhc_callers_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_callers',
            name='caller_status',
            field=django_enumfield.db.fields.EnumField(enum=hhcweb.models.caller_status_enum, null=True),
        ),
    ]
