# Generated by Django 4.2.1 on 2023-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0030_agg_hhc_callers_caller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_patients',
            name='Suffered_from',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
