# Generated by Django 4.2.1 on 2023-07-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0031_agg_hhc_patients_suffered_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_patients',
            name='Hospital_name',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_hospitals',
            name='branch',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
