# Generated by Django 4.2.1 on 2023-07-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0032_agg_hhc_patients_hospital_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_patients',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_patients',
            name='otp_expire_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_hospitals',
            name='branch',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='agg_hhc_app_family_details',
        ),
    ]
