# Generated by Django 4.2.2 on 2023-07-05 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0033_agg_hhc_patients_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_patients',
            name='hhc_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_hospitals'),
        ),
    ]
