# Generated by Django 4.2.2 on 2023-07-06 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0035_rename_hhc_code_agg_hhc_patients_hosp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_sub_services',
            name='srv_id',
        ),
        migrations.AddField(
            model_name='agg_hhc_app_add_address',
            name='Address_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_add_address',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_add_address',
            name='locality',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_add_address',
            name='patient_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_patients'),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_add_address',
            name='pincode',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_add_address',
            name='sate',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_services',
            name='sub_srv',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='hhcweb.agg_hhc_sub_services'),
        ),
    ]
