# Generated by Django 4.2.2 on 2023-07-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0036_remove_agg_hhc_sub_services_srv_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_services',
            name='sub_srv',
        ),
        migrations.AddField(
            model_name='agg_hhc_sub_services',
            name='srv_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='hhcweb.agg_hhc_services'),
        ),
    ]
