# Generated by Django 4.2.1 on 2023-07-11 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0037_remove_agg_hhc_services_sub_srv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_city',
            name='Added_by',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_city',
            name='Added_date',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_city',
            name='City_name',
        ),
        migrations.AddField(
            model_name='agg_hhc_city',
            name='state_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_state'),
        ),
        migrations.CreateModel(
            name='agg_hhc_pincode',
            fields=[
                ('pincode_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_city')),
                ('state_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hhcweb.agg_hhc_state')),
            ],
        ),
        migrations.AddField(
            model_name='agg_hhc_city',
            name='city_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
