# Generated by Django 4.2.1 on 2023-07-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0038_remove_agg_hhc_city_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_city',
            name='city_name',
        ),
        migrations.AddField(
            model_name='agg_hhc_city',
            name='Added_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_city',
            name='Added_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_city',
            name='City_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
