# Generated by Django 4.2.1 on 2023-05-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='agg_hhc_app_caller_register',
            fields=[
                ('app_call_reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.IntegerField(null=True)),
                ('otp', models.IntegerField(null=True)),
                ('otp_expire_time', models.DateTimeField(null=True)),
                ('fname', models.CharField(max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=50, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('house_no', models.CharField(max_length=50, null=True)),
                ('town', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('save_this_add', models.CharField(max_length=50, null=True)),
                ('added_date', models.DateField(null=True)),
            ],
        ),
    ]
