# Generated by Django 4.2.1 on 2023-07-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agg_hhc_app_add_address',
        ),
    ]
