# Generated by Django 4.2.1 on 2023-05-31 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_app_caller_register',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_caller_register',
            name='contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_caller_register',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
