# Generated by Django 4.2.1 on 2023-05-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0003_agg_hhc_app_caller_register_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_app_caller_register',
            name='added_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
