# Generated by Django 4.2.1 on 2023-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0004_alter_agg_hhc_app_caller_register_added_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_app_caller_register',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
