# Generated by Django 4.2.1 on 2023-06-01 09:48

from django.db import migrations, models
import hhcapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0005_alter_agg_hhc_app_caller_register_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_hhc_app_family_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_call_reg_id', models.IntegerField(null=True)),
                ('phone', models.BigIntegerField(null=True)),
                ('otp', models.IntegerField(null=True)),
                ('otp_expire_time', models.DateTimeField(null=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact', models.BigIntegerField(null=True)),
                ('Address', models.CharField(max_length=250)),
                ('save_this_add', models.CharField(max_length=250)),
                ('added_date', models.DateField(null=True)),
                ('profile_pic', models.ImageField(null=True, upload_to='')),
                ('status', models.EmailField(max_length=254, null=True, verbose_name=hhcapp.models.status_enum)),
            ],
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_caller_register',
            name='house_no',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_caller_register',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_caller_register',
            name='state',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_caller_register',
            name='town',
        ),
        migrations.AddField(
            model_name='agg_hhc_app_caller_register',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
