# Generated by Django 4.2.1 on 2023-06-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hhcweb', '0016_alter_agg_hhc_services_image_path'),
        ('hhcapp', '0006_agg_hhc_app_family_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_app_family_details',
            name='app_call_reg_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_family_details',
            name='id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_family_details',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='agg_hhc_app_family_details',
            name='family_member_id',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agg_hhc_app_family_details',
            name='relation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hhcweb.agg_hhc_caller_relation'),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='Address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='save_this_add',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='agg_hhc_app_add_address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500, null=True)),
                ('app_call_reg_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hhcapp.agg_hhc_app_caller_register')),
            ],
        ),
    ]
