# Generated by Django 4.2.1 on 2023-06-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0007_remove_agg_hhc_app_family_details_app_call_reg_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agg_hhc_app_caller_register',
            name='alter_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_family_details',
            name='alter_contact',
            field=models.BigIntegerField(null=True),
        ),
    ]
