# Generated by Django 4.2.1 on 2023-06-02 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0008_agg_hhc_app_caller_register_alter_contact_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agg_hhc_app_caller_register',
            old_name='app_call_reg_id',
            new_name='app_user_id',
        ),
        migrations.AddField(
            model_name='agg_hhc_app_family_details',
            name='app_user_id',
            field=models.IntegerField(null=True),
        ),
    ]
