# Generated by Django 4.2.1 on 2023-06-02 09:24

from django.db import migrations
import django_enumfield.db.fields
import hhcapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0009_rename_app_call_reg_id_agg_hhc_app_caller_register_app_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcapp.models.status_enum, null=True),
        ),
    ]
