# Generated by Django 4.2.1 on 2023-06-05 06:08

from django.db import migrations, models
import hhcapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0010_alter_agg_hhc_app_family_details_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agg_hhc_app_caller_register',
            old_name='app_user_id',
            new_name='app_call_reg_id',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_caller_register',
            name='alter_contact',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_family_details',
            name='alter_contact',
        ),
        migrations.RemoveField(
            model_name='agg_hhc_app_family_details',
            name='app_user_id',
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='status',
            field=models.EmailField(max_length=254, null=True, verbose_name=hhcapp.models.status_enum),
        ),
    ]
