# Generated by Django 4.2.1 on 2023-06-05 06:16

from django.db import migrations, models
import django_enumfield.db.fields
import hhcapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0011_rename_app_user_id_agg_hhc_app_caller_register_app_call_reg_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agg_hhc_app_caller_register',
            old_name='app_call_reg_id',
            new_name='app_user_id',
        ),
        migrations.AddField(
            model_name='agg_hhc_app_caller_register',
            name='alter_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_family_details',
            name='alter_contact',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agg_hhc_app_family_details',
            name='app_user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='agg_hhc_app_family_details',
            name='status',
            field=django_enumfield.db.fields.EnumField(enum=hhcapp.models.status_enum, null=True),
        ),
    ]
