# Generated by Django 4.2.1 on 2023-06-07 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0012_rename_app_call_reg_id_agg_hhc_app_caller_register_app_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agg_hhc_app_family_details',
            name='relation',
        ),
        migrations.DeleteModel(
            name='agg_hhc_app_add_address',
        ),
        migrations.DeleteModel(
            name='agg_hhc_app_caller_register',
        ),
        migrations.DeleteModel(
            name='agg_hhc_app_family_details',
        ),
    ]
