# Generated by Django 4.2.1 on 2023-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hhcapp', '0013_remove_agg_hhc_app_family_details_relation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agg_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
