# Generated by Django 4.2.1 on 2023-06-12 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hhcapp', '0016_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agg_hhc_app_add_address',
        ),
    ]
